package items

import (
	"errors"

	"github.com/sampado/bookstore_items-api/clients/elasticsearch"
	"github.com/sampado/bookstore_utils-go/rest_errors"
)

const (
	indexItems = "items"
)

func (i *Item) Save() rest_errors.RestError {
	result, err := elasticsearch.Client.Index(indexItems, i)
	if err != nil {
		return rest_errors.NewInternalServerError("Error persisting the item", errors.New("database error"))
	}

	// use as Item ID the ID generated by Elastic Search
	i.Id = result.Id

	return nil
}
